# Generated by Django 5.1 on 2024-09-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_attendance_attendance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='User_type',
            field=models.CharField(choices=[('1', 'HOD'), ('2', 'STAFF'), ('3', 'STUDENT')], default='1', max_length=50),
        ),
    ]
