# Generated by Django 5.1.1 on 2024-09-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_alter_customuser_user_type_studentresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="subject_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.subject"
            ),
        ),
        migrations.AlterField(
            model_name="attendance_report",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.student"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.course"
            ),
        ),
    ]
